name: Build and Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Application deploy
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.3.2
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} 
        build_configuration: production
        base_href: /task-clicker/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/task-clicker
